apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicast-oracle
  labels:
    app: apicast-oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicast-oracle
  template:
    metadata:
      labels:
        app: apicast-oracle
    spec:
      containers:
      - name: apicast-oracle
        image: magdamartinez/apicast:latest
        ports:
        - containerPort: 8080
          name: proxy
        - containerPort: 8090
          name: management
        env:
        - name: THREESCALE_PORTAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: apicast-configuration-url-secret
              key: AdminPortalURL
--- 

kind: Service
apiVersion: v1
metadata:
  name: apicast-oracle
spec:
  type: LoadBalancer
  selector:
    app: apicast-oracle
  ports:
  - name: proxy
    port: 8080
    targetPort: 8080
  - name: management
    port: 8090
    targetPort: 8090


