kind: Service
apiVersion: v1
metadata:
  name: serviceas
spec:
  type: LoadBalancer
  selector:
    app: mft
  ports:
  - name: sftp
    port: 8022
    targetPort: 8022
  - name: https
    port: 8443
    targetPort: 8443
