kind: Service
apiVersion: v1
metadata:
  name: servicemg
spec:
  type: LoadBalancer
  selector:
    app: mft
  ports:
  - name: management1
    port: 8000
    targetPort: 8000
  - name: management2
    port: 8001
    targetPort: 8001
