apiVersion: apps/v1
kind: Deployment
metadata:
  name: mft
  labels:
    app: mft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mft
  template:
    metadata:
      labels:
        app: mft
    spec:
      containers:
      - name: mft
        image: helpsystems/goanywhere-mft:latest
        name: goanywhere-mft
        ports:
        - containerPort: 8000
          name: management1
        - containerPort: 8001
          name: management2
        resources: {}

